### PR TITLE
Fix an issue with compilation lagging a step behind

### LINKED ISSUE #13: Compilation an Iteration Behind
I've noticed that when I make a change to my `lib.rs`, and then run `cargo android run`, the old version of my code runs, not the new version. Then upon second invocation the new version runs.

This sounds very similar to what @Zeerooth experienced in #2 where the first run fails, but the second run includes the `.so` library. 

I suspect some compilation step lags behind.

### PR DESCRIPTION
**Pull request by Zeerooth**
Fix #13

### CODE REVIEW

**Comment by francesca64** [comment]
Thanks so much for making PRs!

This is actually how `cargo android run` worked in the past. If I'm not mistaken, this breaks the existing workflow for anyone using Android Studio, since now they'd have to run `cargo android build` before Android Studio would have the lib.

**Comment by Zeerooth** [comment]
> Thanks so much for making PRs!

No problem, I'm happy to contribute in some way :)

> If I'm not mistaken, this breaks the existing workflow for anyone using Android Studio, since now they'd have to run `cargo android build` before Android Studio would have the lib.

If you're referencing how `cargo-mobile` works right now, that's true. Running `cargo android build` and then `cargo android run` works well. But, of course, this workflow shouldn't function like that and `cargo android run` should build the library correctly.

> This is actually how `cargo android run` worked in the past. 

Do you know why this was changed in the first place? I don't want to break any existing features unintentionally.

**Comment by francesca64** [comment]
> Do you know why this was changed in the first place?

I changed it because it didn't support an Android Studio/gradle-only workflow. One of cargo-mobile's design goals is that you can work from Android Studio/Xcode in a fairly normal way, in addition to also providing you with an equally first-class option of working from the command line.

The benefit of the plugin is that you can build from within Android Studio, instead of having to remember to run `cargo android build` beforehand. While some users will prefer to use `cargo android run`, running from Android Studio is an equally important use-case.

**Comment by Zeerooth** [comment]
Well, I guess you're right that supporting Android Studio workflow is somewhat important... But I don't have a solution yet that will both fix the problems with linking the native rust library in `cargo android run` and when running the project via Android Studio/with gradlew. I spent some time on this and I think that's straight up impossible to use gradle plugins to build and link native libraries to builds (but it would be great if somebody could prove me wrong) so I'll try to come up with an alternative solution later when I have time. 

Thanks for the help

**Comment by Zeerooth** [comment]
@francesca64 I updated this pull request with new solution, turns out that I was wrong and just depending on `merge{arch}JniLibFolders` instead of `assemble{arch}` is enough to fix the issue with compilation lagging behind, can't believe I didn't think of that much earlier lol

**Review by francesca64 — APPROVED** [review]
This is fantastic! You've fixed a very annoying long-standing bug.

(I thought I fixed it back in 1be593389e7dcb0b2818b8e63b070f8a1aa31c3a, but evidently I didn't test that very thoroughly...)

**Pull request merged**
